### ISSUE TITLE
Python 3 can't import st

### ISSUE THREAD

**Issue by BubbaRich** [claudiodsf/stockwell#1]
I'm probably forgetting something obvious, but when I start Python 3 in the main directory, it can't import st from stockwell:

```
>>> from stockwell import st
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bubbarich/Documents/GitHub/stockwell/stockwell/__init__.py", line 1, in <module>
    from .lib import st
ImportError: cannot import name 'st'
```

I'm not familiar enough with importing from externally-defined namespaces to know how it is supposed to work.  I tried several variations, and building and installing the project again.

**Comment by claudiodsf** [comment]
When you build and install the package, the python files and the compiled shared libraries are copied to the `site-packages` directory. In my case, for instance, this directory is:
```bash
$HOME/anaconda3/lib/python3.6/site-packages/stockwell/lib
```
In this directory, you will find the two shared libraries: `sine.cpython-36m-darwin.so` `st.cpython-36m-darwin.so` (or similar names).

If you open a Python interpreter from any folder of your file system and import `stockwell`, it will use the `site-packages` version of the library:

```python
>>> import stockwell
>>> stockwell.__path__
['/Users/claudio/anaconda3/lib/python3.6/site-packages/stockwell']
```
and it will be able to find the shared libraries.

However, if you run `python` from within the top level directory of the project, it will use the local version of the library:

```python
>>> import stockwell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/claudio/Lavoro/Programmi/mysw/stockwell/stockwell/__init__.py", line 1, in <module>
    from .lib import st
ImportError: cannot import name 'st'
```

(you see that it tries to import from a different directory -- `/Users/claudio/Lavoro/Programmi/mysw/stockwell/stockwell` in my case).

For a standard installation, the local `lib` directory (`/Users/claudio/Lavoro/Programmi/mysw/stockwell/stockwell/lib` in my case; `/Users/bubbarich/Documents/GitHub/stockwell/stockwell/lib`, in your case) does not contain the compiled shared libraries.

There are two solutions:
1. (the easiest) run `python` from outside the project main dir
2. install the package in "editable" mode (`pip install -e .`), this will put the shared libraries in your local `lib` dir.

**Comment by BubbaRich** [comment]
Thank you very much for the clear and complete explanation!

I'm creating a branch to specialize in audio wav files in my local
repository, with standard libraries.  If it works well and flexibly (even
for different formats and mono/stereo), I'll let you know.

Rich

**Comment by claudiodsf** [comment]
Great! Don't hesitate creating a pull request :wink:

**Comment by ghost** [comment]
freqmin and freqmax are defined as integer and should be real number (to work at long period....)

**Comment by claudiodsf** [comment]
Hi @Stutzmann,

This was indeed not clear from the example: `st.st()` wants integer frequency as input, defined as real frequency (in Hz) divided by the frequency sampling step (which is `1./signal_length`).

I updated the example to make it clearer.

Next time, please open a new issue (green button "new issue" on the upper right), instead of reusing an existing one 😉

**Comment by saharsalimpour** [comment]
Hi @claudiodsf 
I got this error : 
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-4e6a9348fdb1> in <module>
      2 from scipy.signal import chirp
      3 import matplotlib.pyplot as plt
----> 4 from stockwell import st
      5 
      6 t = np.linspace(0, 10, 5001)

~\stockwell\__init__.py in <module>
----> 1 from .lib import st
      2 from .lib import sine
      3 
      4 __version__ = 1.0

ModuleNotFoundError: No module named 'stockwell.lib'
Could you help me?
thanks
