### ISSUE TITLE
Stockwell and Obspy

### ISSUE THREAD

**Issue by joamanuel** [claudiodsf/stockwell#10]
Hello, I have a problem when I try to use obspy stockwell with obspy. The problem exactly is:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_101293/699505916.py in <module>
      3 from obspy import read
      4 from scipy.signal import hilbert
----> 5 from stockwell import st

~/anaconda3/envs/obspy/lib/python3.9/site-packages/stockwell/__init__.py in <module>
      1 """Time-frequency analysis through Stockwell transform."""
----> 2 from .lib import st  #NOQA
      3 from .lib import sine  #NOQA
      4 from ._version import get_versions
      5 __version__ = get_versions()['version']

ImportError: numpy.core.multiarray failed to import

This problem, I think is a problem with numpy version. I try to solve this installing version 1.23.0, but obspy doesn't work.

Do you have some options? 

Thanks in advance

Joan

**Comment by claudiodsf** [comment]
Hi, which version of ObsPy are you using?

**Comment by joamanuel** [comment]
Hello Claudio, 

I'm using version 1.2.2

Thanks

**Comment by claudiodsf** [comment]
ObsPy 1.3.0 was released this year with compatibility fixes for recent NumPy version. 

Would it be possible for you to install the most recent ObsPy?

**Comment by joamanuel** [comment]
Ok, I'm going to re-install obspy 1.3.0 and try again.

I let you know if it worked.

Thanks

**Comment by joamanuel** [comment]
Everything OK

Thanks!

**Comment by claudiodsf** [comment]
Great! Closing this issue, then.
