### ISSUE TITLE
Could not install stockwell

### ISSUE THREAD

**Issue by AmirSarrafzadeh** [claudiodsf/stockwell#11]
Dear claudio,

I hope you are doing well,

I am trying to install the stockwell in my machine, I have Windows 11 OS, but it gives me strange errors.

I downloaded the source code and put inside site-paclages and when I want to import the library it gives me this error.

FileNotFoundError: Could not find module 'mylocalpath\Lib\site-packages\stockwell\lib\st.cp312-win_amd64.pyd' .

I checked the website (https://pypi.org/project/stockwell/#files)

but the latest version for this file is 
stockwell-1.1-cp310-cp310-win_amd64.whl.

Best regards,

Amir

**Comment by claudiodsf** [comment]
Dear Amir,
sorry for late reply.

I assume that you run Python 3.12.

I just released Stockwell v1.1.1, which supports Python 3.11 and 3.12.

Could you please try:

     pip install --upgrade stockwell

?

**Comment by AmirSarrafzadeh** [comment]
Dear Claudio,

I hope you are doing well,

I solved the issue and it works fine now.

Thank you again for your message

take care and have a nice day

Amir Sarrafzadeh Arasi

**Comment by claudiodsf** [comment]
Great! All the best!
