### ISSUE TITLE
does the gamma and window paprameters are included in the stoackwell transfrom ?

### ISSUE THREAD

**Issue by chiseo36** [claudiodsf/stockwell#5]
gamma = 1.3
window = 'gauss' # or 'kazemi'
st.st(data, window, gamma, 100, 1800)

Does it included in the stockwell transfrom .

when i implement something like this stock = st.st(w, window, gamma, fmin_samples, fmax_samples)
I am getting error as
TypeError: function takes at most 3 arguments (5 given)

**Comment by chiseo36** [comment]
I made the solution for my question.Thanks.

**Comment by claudiodsf** [comment]
Hi, I just merged the pull request #4 which adds `gamma` and `win_type`.

Could you please test the code?

Note that the function signature is slightly different (different order of parameters):
```python
st.st(x, lo=0, hi=0, gamma=1, win_type='gauss')
```
