### ISSUE TITLE
Hi buddy，is there an official documentation?

### ISSUE THREAD

**Issue by YANKT** [claudiodsf/stockwell#8]
Recently I've been studying the S-transform，prepare to use the S-transform in the my paper,I used it in Matlab，but I want to do it in Python，could you provide API documentation for Python?Thx

**Comment by claudiodsf** [comment]
Hy YANKT, sorry no documentation for the moment: just the README of this repository 😉 

Unfortunately I don't have time right now to write a thorough documentation...

**Comment by YANKT** [comment]
All right，thank you for your reply.Mind if I pick your brains for a minute? I need to convert a one-dimensional EEG signal into a two-dimensional matrix (spectrogram) for input to CNN, similar to the short-time fourier transform. Which interface should I use?
[MATLAB.zip](https://github.com/claudiodsf/stockwell/files/8570334/MATLAB.zip)
This is the S transform in MATLAB，If you're interested in this ,you may go and see it.I want to use your S transform in Python, but don't know how :(
